<?php

/**
 * Implements hook_theme().
 */
function time_location_theme($existing, $type, $theme, $path) {
    return [
      'block-time-location' => [
        'variables' => [
          'dateValue' => null,
         ],
          
      ],
    ];
} 

function hook_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  if ($form_id == 'timezone_settings') {
    $form['elements']['country']["#default_value"] = "India";
 }
}

?>